# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: keto-calculator_development
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432

test: &test
  <<: *default
  database: keto-calculator_test
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  host: localhost
  port: 5432

production:
  <<: *default
  database: keto-calculator_production
  username: keto-calculator
  password: <%= ENV['KETO-CALCULATOR_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test